### ISSUE TITLE
Negative Test Cases -  Unexpected inputs

### ISSUE THREAD

**Issue by janithDakshitha** [rajin4463/Centinal#3] opened 2023-07-08 11:59 UTC
The following problem was encountered while testing the relevant code under unexpected input handling conditions in the script:
**Test case - Validate error handling for an invalid inputs**
- input : "w"
- Expected output : "Invalid input! Try again"
- Output : 
![unexpected_input](https://github.com/rajin4463/Centinal/assets/107628399/c5a280be-fddd-4a31-bccd-ad1d14a13496)

**Comment by rajin4463** [comment] 2023-07-08 12:23
**Status:**
_Fix Pending_

**Cause**
`The issue is caused by the user input immediately being converted into an integer.`

**Possible Solution**
`Take inputs in string format and do validations or add a try-except block`

**Comment by rajin4463** [comment] 2023-07-08 12:52
**Status:**
_Fixed_

issue fixed in commit 16bf03d

**Closed as completed by rajin4463** 2023-07-08 12:52 UTC
Labels: bug, unexpected
